name: Download package.json files

on:
  workflow_dispatch:
    inputs:
      repo:
        description: "Repo Name"
        required: true

env:
  REPO: ${{ github.event.inputs.repo }}        

jobs:
  download-package-json:
    runs-on: ubuntu-latest

    steps:
      - name: Sparse checkout another repo
        run: |
          git clone --no-checkout https://github.com/Sunilsindur/$REPO remote-repo
          cd remote-repo
          git sparse-checkout init --cone
          echo "*package.json" >> .git/info/sparse-checkout
          echo "*demo.json" >> .git/info/sparse-checkout
          git checkout

      - name: bash script to copy package.json files or demo.json files with there dir name
        run: |
          mkdir -p ../json-files
          find . -type f \( -name "package.json" -o -name "demo.json" \) -exec bash -c 'mkdir -p ../json-files/$(dirname "{}"); cp "{}" ../json-files/$(dirname "{}")' \;

      - name: display directories name and content of files
        run: |
          cd ../json-files
          pwd
          ls
          echo "Folders containing package.json or demo.json files and their contents:"
          find . -type f \( -name "package.json" -o -name "demo.json" \) | while read file; do
            ls
            folder_name=$(basename "$(dirname "$file")")
            echo "------------------------------------------"
            echo "Folder: $folder_name"
            echo "Contents of $file:"
            cat "$file"
            echo "------------------------------------------"
          done

          



          
