name: Cron Job Example

on:
  schedule:
    - cron: '0 0 * * *'
    - tz: 'America/Chicago'

jobs:
  run-cron-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Python script
        run: |
          python3 your_script.py
